image:
  file: .cde.Dockerfile

tasks:
  - name: Install Tools
    init: |
      pip3 install -r requirements.txt
  - name: Azure Login
    command: |
      sh ./cde/azure_login_sp.sh
      gp sync-done azure_login
  - name: Versions
    command: |
      sh ./cde/environment_versions.sh
  - name: Variables
    command: |
      sh ./cde/environment_variables.sh
  - name: Configure Databricks
    command: |
      gp sync-await azure_login
      sh ./cde/databricks_configure.sh
      gp sync-done wait_on_databricks

vscode:
  extensions:
    - ms-python.python
    - mtxr.sqltools
    - databricks.databricks
    - databricks.sqltools-databricks-driver