image:
  file: .cde.Dockerfile

tasks:
  - name: Install Tools
    init: |
      sh ./cde/install_tools.sh
  - name: Azure Login
    command: |
      sh ./cde/azure_login_sp.sh
  - name: Versions
    command: |
      sh ./cde/environment_versions.sh
  - name: Variables
    command: |
      sh ./cde/environment_variables.sh
  - name: Configure Databricks
    command: |
      sh ./cde/databricks_configure.sh
  - name: Example Spark Shell
    command: |
      sh ./cde/spark_run.sh
  - name: Example Pyspark
    command: |
      python ./cde/main.py

vscode:
  extensions:
    - ms-python.python
    - databricks.databricks
    - databricks.sqltools-databricks-driver