image:
  file: .cde.Dockerfile

tasks:
  - name: Install Tools
    before: |
      sh ./cde/install_tools.sh
  - name: Azure Login
    command: |
      sh ./cde/azure_login_sp.sh
      gp sync-done azurelogin
  - name: Versions
    command: |
      sh ./cde/environment_versions.sh
  - name: Variables
    command: |
      sh ./cde/environment_variables.sh
  - name: Configure Databricks
    command: |
      gp sync-await azurelogin
      sh ./cde/databricks_configure.sh
      gp sync-done waitondatabricks
  - name: Example Spark Shell
    command: |
      sh ./cde/spark_run.sh
  # - name: Example Pyspark
  #   command: |
  #     python ./cde/main.py
  - name: Template DAB Deploy
    command: |
      gp sync-await waitondatabricks
      sh ./cde/databricks_deploy.sh

vscode:
  extensions:
    - ms-python.python
    - databricks.databricks
    - databricks.sqltools-databricks-driver