image:
  file: .cde.Dockerfile

tasks:
  - init: pip3 install -r requirements.txt
  - name: Versions
    command: |
      sh ./cde/environment_versions.sh
  - name: Variables
    command: |
      sh ./cde/environment_variables.sh
  - name: Configure Databricks
    command: |
      sh ./cde/databricks_configure.sh
  - name: Example Spark Shell
    command: |
      sh ./cde/spark_run.sh
  - name: Example Pyspark
    command: |
      python ./cde/pyspark.py

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-python.python
    - databricks.databricks